files:
    raw:
      raw_data: "${paths.data_raw}convolve-epoch1.zip"
      json_file: "${paths.data_raw}train.json"
      parquet_file: "${paths.data_raw}raw_parquet"
      raw_train_data: "${paths.data_raw}raw_train_data.gzip"
      raw_valid_data: "${paths.data_raw}raw_valid_data.gzip"
      raw_test_data: "${paths.data_raw}raw_test_data.gzip"
      dev_zip: "${paths.dev}dev.gzip"
      
    processed:
      train_dataset: "${paths.data_processed}train.gzip"
      valid_dataset: "${paths.data_processed}valid.gzip"
      test_dataset: "${paths.data_processed}test.gzip"

paths:
  data_raw: ${hydra:runtime.cwd}/data/raw/
  data_processed: ${hydra:runtime.cwd}/data/processed/
  dev: ${hydra:runtime.cwd}/dev/

params:
  batch_size: 32
  total_epochs: 2

model_name:
  "1DCNN"